### ISSUE TITLE
[API] - Get Data from Device

### ISSUE THREAD

**Issue by JLefebvre55** [CloudClub-uoft/iot-device#15]
Write the `GET` API route at `/device/getData` to request data based on device ID and timestamp. 
This API will be used by the front-end team to pull data for their React Chart components. This API should return data requested for the specific deviceId and data label.

Queries for data added _between_ a specific date and time. **NOTE**: This functionally will be eventually added; however, it is not an immediate requirement. For initial iteration, it will be sufficient to return just the latest 10 data points specific to the query. 

**Inputs**: Device Id, Topic
**Output**: JSON structure as defined below. The JSON structure return in the response will hold a key called "data" and its value will be an array which holds data points relevant to the query.

### Response Object
```json
{
  "data" : {
    "topic" : "temperature",
    "timestamp" : 152785725,
    "value" :  23.6
  }
}
```

> EDIT (Jayden): "For now, we're going to start with just getting the latest datapoint for a given device and topic"

TODO:
- [ ] Building a `GET` route at '/device/getData' ([Express.JS](https://expressjs.com/en/guide/routing.html))
- [ ] Encoding input parameters (device ID, topic) into the `GET` request ([**URL parameters** with Express.JS](https://expressjs.com/en/guide/routing.html), i.e. `/device/getData?topic=temperature&deviceid=152`)
- [ ] MongoDB request for the latest data point for that device (???)
- [ ] **EITHER**: 
  - [ ] IF FOUND: Return data (see JSON above) with success code (200)
  - [ ] IF NOT FOUND: Return code 404
  - [ ] OTHER ERROR: Return 500 (try/catch)

**Comment by JLefebvre55** [comment]
@harsimrat99 wondering if you can clarify the specifics of the request and response of this route :)

Also, waiting on Terry to accept the org invite. DM'd him on slack

**Comment by harsimrat99** [comment]
@JLefebvre55 Could you please let us know about the updates from @terryluan12 on this issue. I will be assigning this issue to @Lepabryce in the meantime to get thing moving.

**Comment by JLefebvre55** [comment]
- [ ] Building a `GET` route at '/device/getData' ([Express.JS](https://expressjs.com/en/guide/routing.html))
- [ ] Encoding input parameter (device ID) into the `GET` request ([**URL parameters** with Express.JS](https://expressjs.com/en/guide/routing.html), i.e. `/device/getData?deviceid=152`)
- [ ] MongoDB request for the latest data point for that device (???)
- [ ] **EITHER**: 
  - [ ] IF FOUND: Return data `{ "data" : 1.524 }` with success code (200)
  - [ ] IF NOT FOUND: Return code 404
  - [ ] OTHER ERROR: Return 500 (try/catch)
