### ISSUE TITLE
/device/info mac address query 

### ISSUE THREAD

**Issue by harsimrat99** [CloudClub-uoft/iot-device#32]
There is an issue with the /device/info API where the MAC address being queried is not resolving in a found device even when the  deviceId exists in the database. 

To recreate this issue:
Please initiate a GET request as follows; GET localhost:3000/device/info?mac=99ed863da747 .

The device with this deviceId exists in the database with the following values.
![image](https://user-images.githubusercontent.com/39355613/124534215-c5bfe600-dde1-11eb-8789-9cd4bbc55d17.png)

Postman routine is shown in the attached video. 
https://user-images.githubusercontent.com/39355613/124534495-644c4700-dde2-11eb-8b3a-4648a0458c97.mp4

**Comment by matt8100** [comment]
I am unable to reproduce the issue. Both the VS Code REST client and a simple browser GET seem to work for me.
![image](https://user-images.githubusercontent.com/12620259/124542808-f0597100-ddd8-11eb-8e4d-1bbcd93e35d1.png)
![image](https://user-images.githubusercontent.com/12620259/124543064-6958c880-ddd9-11eb-8ca1-7895a9caf2ab.png)

Edit: Installed PostMan and it also seems to work. Can you confirm that you're on the latest version of staging?
![image](https://user-images.githubusercontent.com/12620259/124543834-db7ddd00-ddda-11eb-8d17-17f2f49ef786.png)

**Comment by harsimrat99** [comment]
I am still unable to make a successful request. I have also pulled the latest staging branch and I have tried other MAC addresses as well.

GET http://localhost:3000/device/info?mac=0370e9b28ed3

**Comment by matt8100** [comment]
What about in the browser? It's still working for me.
![image](https://user-images.githubusercontent.com/12620259/124687761-65d14a00-de8a-11eb-9c4b-104b80705eb8.png)

**Comment by iWebster28** [comment]
Able to reproduce issue with /device/info following device registration with hyphen separators instead of colons for "deviceId" in /device/register route. i.e. xx-xx-xx-xx-xx-xx

No issue with /device/info following device registration with a "deviceId" with colon separators. i.e. xx:xx:xx:xx:xx:xx

**Comment by matt8100** [comment]
Got it, device/info will reformat the query with colons to search the database, so it won't find ones with dashes. @harsimrat99 is there a particular format we should enforce for registration (colons or dashes)? Or should it be symbol-independent, wherein we save the MAC address without any symbols at all.

**Comment by harsimrat99** [comment]
@matt8100 let's store MAC addresses in the database without any colons or dashes as String data types. Colons are added just for the sake of readability. For consistency let us keep the strings as all lowercase.

**Comment by matt8100** [comment]
@harsimrat99 should colon or dash formatting still be required when registering a device?

**Comment by harsimrat99** [comment]
@matt8100 I believe we can keep things simple by removing the need for colons or dashes. Just a hex string should be fine.
