### ISSUE TITLE
[TEST] - Non-functioning Mocha tests

### ISSUE THREAD

**Issue by matt8100** [CloudClub-uoft/iot-device#35]
Current non-functioning tests:
- [x] POST data/blob
- [x] GET data/getData (route file is wrongly named, test file is wrongly named)
- [x] GET device/info
- [x] POST data/new (route file is wrongly named, test file is wrongly named)

The /data routes also have style issues. Please use ESLint to ensure consistent style and convention.

**Comment by harsimrat99** [comment]
@Lepabryce @Golem8 
Team, let's ensure that the tests are passing. Please check for failing tests as mentioned by Matt before we make any other pull requests. Thank you.

**Comment by Golem8** [comment]
The test passes when using the github version of formidable. #34 makes formidable 2.x.x a dependency, and the fileWriteStreamHandler method used to upload to s3 was added in formidable 3.x.x

Is it possible to modify the automated test using something like [this](https://github.com/actions/setup-node/issues/214#issuecomment-810829250), and go back to using the github version of formidable?

**Comment by harsimrat99** [comment]
@matt8100
