### ISSUE TITLE
[SEC] - Device Self-Registration and Cert Requests

### ISSUE THREAD

**Issue by JLefebvre55** [CloudClub-uoft/iot-device#41]
Make a device-facing HTTP GET route for generating and serving certificates. Similar to #30 

Devices should have hard-coded CloudClub login info (user+pass) that they pass to this endpoint (URL params) to request a certificate they use for authentication to the MQTT broker and HTTP data push endpoints.

**Comment by matt8100** [comment]
Are there any security concerns with passing user logins by URL parameters?

**Comment by JLefebvre55** [comment]
> Are there any security concerns with passing user logins by URL parameters?

@matt8100 I think as long as it's HTTPS we should be ok
