### ISSUE TITLE
[REPO] - Organize: Group Routes by Purpose

### ISSUE THREAD

**Issue by JLefebvre55** [CloudClub-uoft/iot-device#42]
Sort route files into device-facing `/routes/device` and webapp backend `/routes/backend`

[Edit]
As discussed our goal is to organize the methods into 2 groups; '/api' for IoT devices and another group that is for authenticating and general querying.

At the time of writing, the routes folder looks as follows:
    
routes
    --auth
    --data
    --device

The reorganized routes folder should look like this:
routes
    --auth 
    --api
    --backend

The api folder should contain the methods that were previously made for uploading data; i.e. /data/blob and /data/new.
The final URLs for APIs should look like **/api/data/blob**, and **/api/data/new**

All other routes that are necessary for registering devices, unregistering devices, querying data, etc., should be placed under the backend folder.
The final URLs for the backend route may look like **/data/getData**, **/device/register**, etc. Please keep in mind that there is no explicit **/backend** address required in these routes.

**Comment by matt8100** [comment]
I renamed the `/backend` folder to `/device because that seems to make more sense if `/backend` just represents all device-facing routes. I also put the auth folder into `/api` because those are webapp-facing.
