### ISSUE TITLE
API - Unregister Device

### ISSUE THREAD

**Issue by JLefebvre55** [CloudClub-uoft/iot-device#5]
Develop an HTTP API route for unregistering devices. See `/controllers/device.js`

**INPUT**: deviceid
**PROCESS**: Deletes the device associated with this deviceid from the database
**OUTPUT**: Success (200) or Failure (40X)

**Comment by harsimrat99** [comment]
@Golem8 It would be great if you could please create test cases for the unregister function. It should perform the following steps:

Thank you for the updates. It would be helpful if you could please create a test case before we merge the changes into the staging branch. The test case should be placed inside the test folder and it should perform the following steps:

1. Register a temporary Device into the MongoDB database.
2. Remove the temporary device by calling your API.
3. Ensure that the device has been removed successfully. 

The test cases should be placed in the test folder and it must assert that the device has been successfully removed using your unregisterDevice function.
