### ISSUE TITLE
[DOCS] Create route documentation.

### ISSUE THREAD

**Issue by matt8100** [CloudClub-uoft/iot-device#59]
We should really start documenting our routes because we shouldn't have to read code to figure out what something does.

I think we can implement the same thing we did for the website, [apidoc](https://apidocjs.com/), since it looks nice, allows documentation to be contained and structured in each route's individual file, and can be automated.

- [ ] Document all routes. Comments should be just before the `module.exports` of a route (after the `require()`s). See [apidoc](https://apidocjs.com/) documentation for how to write inline documentation.
  - [ ] `POST-blob`
  - [ ] `POST-new`
  - [ ] `GET-cert`
  - [ ] `POST-cert`
  - [ ] `POST-login`
  - [ ] `GET-getData`
  - [ ] `GET-info`
  - [ ] `POST-register`
  - [ ] `POST-unregister`
- [ ] Setup a GitHub workflow to automatically generate apidocs on push to staging ONLY when a route file is modified. We can choose to either serve the docs ourselves, or have it moved to a `gh-pages` branch and have GitHub Pages serve it. The latter seems easier to do, and it's simple enough to have it served under our own subdomain as well.

**Comment by harsimrat99** [comment]
@CloudClub-uoft/backend . Let's start making use of the Wiki functionality in GitHub to create documentation on routes and data models.

**Comment by harsimrat99** [comment]
I will help with documenting the deployment and configuration of the server. But route developers should provide some documentation of their routes as per Matt's comments.

**Comment by matt8100** [comment]
@harsimrat99 do you want us to use GitHub wikis or apidoc

**Comment by harsimrat99** [comment]
@matt8100 Let's try using GH wiki for this project.

**Comment by harsimrat99** [comment]
By the way, do you see any problems if we use GH Wiki? I guess my only concern is that we won't have the ability to generate API docs if we use the GitHub wiki route.
