### ISSUE TITLE
API - Device Info

### ISSUE THREAD

**Issue by JLefebvre55** [CloudClub-uoft/iot-device#6]
Develop an HTTP API route (**GET**) for fetching device info. See `/controllers/device.js`.

**INPUT**: API key, deviceid
**PROCESS**: the device information is fetched from the database
**OUTPUT**: Success (200) or Failure (40X)

**Comment by JLefebvre55** [comment]
@harsimrat99 I assumed the request had to include the device id. What kind of device info is being published?

**Comment by harsimrat99** [comment]
@JLefebvre55 We should be posting a hardware MAC address for the device id. Whatever device we are using should be able to provide its physical address via an API. For an ESP32 this can be accomplished via WiFi.macAddress() by including <WiFi.h>

**Comment by JLefebvre55** [comment]
@harsimrat99 Currently, `/routes/device.js` includes `deviceInfo` as a **GET** route. Would you like me to change that?

**Comment by harsimrat99** [comment]
@JLefebvre55 I believe I have already asked @Lepabryce to turn it into a GET request. For some reason it has been written as a POST request.

**Comment by JLefebvre55** [comment]
@harsimrat99 Ah. So is it meant to _create new_ device info, or _fetch_ existing info?

**Comment by harsimrat99** [comment]
@JLefebvre55 I believe there has been misunderstanding on my part. The registerDevice (POST) function assigned to @matt8100 is responsible for _creating_ new devices. It has for inputs a MAC address and a friendly name. the deviceInfo (GET) route has been assigned to @Lepabryce and it is responsible for displaying information about devices already registered . This function is supposed to _fetch_ existing info.

**Comment by matt8100** [comment]
I asked Bryce to change it to a POST while helping him with his code. Since according to the comments, the route was to take an API key to get a device's name, I thought it'd be more secure if it was sent through a request body. If it will just be using the MAC address, then we can use URL parameters and a GET.

**Comment by harsimrat99** [comment]
Makes sense. Thank you.

**Comment by JLefebvre55** [comment]
I've updated the original post to reflect this
