### ISSUE TITLE
HTTPS Routing/Forwarding 

### ISSUE THREAD

**Issue by harsimrat99** [CloudClub-uoft/iot-device#63]
This PR is related to #58. As per the new server architecture of 2 Express servers, it is now necessary to determine a way to route requests coming towards *.cloudclub.ca.

Let us assume that we have 2 different servers running on the same host:
1. React backend (**webApp** server) on port 443
2. Device API server (**deviceApp**) on port 8080
And also let's assume that the domain name associated with the host is cloudclub.com. 

The requirement is that **webApp** server should be accessible via the domain webapp.cloudclub.com, and that the **deviceApp** server should be accessible via deviceapp.cloudclub.com. The constraint is that these servers must run on the same host, possibly alongside other applications, which has only a single static IP address associated with it.

These are 2 different subdomains of the same parent domain; i.e. cloudclub.com. Whenever a DNS query is made to either webapp.cloudclub.com or deviceapp.cloudclub.com the answer is the same IP address regardless of which subdomain is used. This gives the requester (either a web browser or an HTTP client) no way to determine which port the specific service it is supposed to connect to. This is problematic because there are 2 ports to choose from, 443 or 8080.

A solution must be determined to effectively route requests coming from the internet to 2 different servers internally on the same host to effectively utilize the machine's resources. 

Possible solution(s): nginx [proxy ](https://stackoverflow.com/a/58122704)server or another request forwarding service. This is an important pre-requisite to deployment and it may require some experimentation and research to be successfully solved.

**Comment by harsimrat99** [comment]
@matt8100 please let me know if my thinking is clear. Feel free to make any edits or clarifications to the issue.

**Comment by Golem8** [comment]
nginx looks like it would require installing another app outside of the node environment, which would probably be complicated. There are some alternatives that could be built in easier like [this](https://www.npmjs.com/package/http-proxy-middleware) and [this](https://www.npmjs.com/package/http-proxy)

**Comment by Golem8** [comment]
Once Bryce's PR is merged in (#62) I can look into this more

**Comment by harsimrat99** [comment]
Hi Simon. Thank you for pointing out the Node.js specific solutions! 

I do think that installing Nginx should not be not too complicated, but I agree that it can get complicated to set it up. I think we should try out the Node.js specific solutions since they seem to be much more straightforward from the first glance.
