### ISSUE TITLE
Ensure Authorized access to /device/info

### ISSUE THREAD

**Issue by harsimrat99** [CloudClub-uoft/iot-device#64]
A requirement of the GET-info route is that it must be accessible only by users who are logged in. Currently the API is accessible without authorization and it can cause data leaks.

This will require adding the JWT middleware to the route as has been implemented for other APIs.

**Comment by Golem8** [comment]
Right now, any logged in user can use the /device/info route on any device (including devices they do not own) provided they have the mac address. Is this the intended functionality?

**Comment by harsimrat99** [comment]
> Right now, any logged in user can use the /device/info route on any device (including devices they do not own) provided they have the mac address. Is this the intended functionality?

Hi Simon,
I think you bring up a good point that it does not make sense that users are able to access data about devices they do not own. Thank you for pointing out this flaw. I am going to create a separate issue to address this.
